GRANT USAGE ON SCHEMA org TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA org TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA org TO admin;
GRANT CREATE ON SCHEMA org TO admin;

GRANT USAGE ON SCHEMA org TO bst_uprav;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA org TO bst_uprav;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA org TO bst_uprav;
GRANT CREATE ON SCHEMA org TO bst_uprav;

GRANT USAGE ON SCHEMA org TO bst_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA org TO bst_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA org TO bst_user;
GRANT CREATE ON SCHEMA org TO bst_user;

GRANT USAGE ON SCHEMA org TO bst_guest;
GRANT select ON ALL TABLES IN SCHEMA org TO bst_guest;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA org TO bst_guest;

GRANT USAGE ON SCHEMA spr TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA spr TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA spr TO admin;
GRANT CREATE ON SCHEMA spr TO admin;

GRANT USAGE ON SCHEMA spr TO bst_uprav;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA spr TO bst_uprav;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA spr TO bst_uprav;
GRANT CREATE ON SCHEMA spr TO bst_uprav;

GRANT USAGE ON SCHEMA spr TO bst_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA spr TO bst_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA spr TO bst_user;
GRANT CREATE ON SCHEMA spr TO bst_user;

GRANT USAGE ON SCHEMA spr TO bst_guest;
GRANT select ON ALL TABLES IN SCHEMA spr TO bst_guest;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA spr TO bst_guest;

GRANT USAGE ON SCHEMA main TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA main TO admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA main TO admin;
GRANT CREATE ON SCHEMA main TO admin;

GRANT USAGE ON SCHEMA main TO bst_uprav;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA main TO bst_uprav;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA main TO bst_uprav;
GRANT CREATE ON SCHEMA main TO bst_uprav;

GRANT USAGE ON SCHEMA main TO bst_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA main TO bst_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA main TO bst_user;
GRANT CREATE ON SCHEMA main TO bst_user;

GRANT USAGE ON SCHEMA main TO bst_guest;
GRANT select ON ALL TABLES IN SCHEMA main TO bst_guest;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA main TO bst_guest;

--GRANT bst_user TO user1;
--GRANT bst_user TO user2;